/** Declaration file generated by dts-gen */
// AttributeType.DATA_TYPE
// https://github.com/graknlabs/grakn/blob/2e6b67bd7a5eb6a64473a65b2221c9de6fab0b74/client-protocol/proto/Concept.proto#L487

export = Grakn;

declare function grakn(a: any, b: any): void

declare class Grakn {
	constructor(uri: string, credentials: any);

	session: any;
	keyspace: any;
	dataType: number;
	txType: number;
}

// enum DATA_TYPE {
//     STRING = 0;
//     BOOLEAN = 1;
//     INTEGER = 2;
//     LONG = 3;
//     FLOAT = 4;
//     DOUBLE = 5;
//     DATE = 6;
// }
declare namespace grakn {
	const dataType: {
		BOOLEAN: 1;
		DATE: 6;
		DOUBLE: 5;
		FLOAT: 4;
		INTEGER: 2;
		LONG: 3;
		STRING: 0;
	};

	const prototype: {};

	// enum Type {
	//     READ = 0;
	//     WRITE = 1;
	//     BATCH = 2;
	// }
	const txType: {
		BATCH: 2;
		READ: 0;
		WRITE: 1;
	};
}
